### ISSUE TITLE
nearcore is also in nixpkgs

### ISSUE THREAD

**Issue by Mic92** [ZentriaMC/neard-nix#1]
Just for your interest: https://github.com/NixOS/nixpkgs/pull/168635/

**Comment by mikroskeem** [comment]
Thank you, however I need to track rc versions (for testnet) and build Docker images for non-NixOS usage until NEAR fixes their image tags, so this flake still has a purpose.

**Comment by Mic92** [comment]
Sure. I also have my own out-of-tree version to test rc versions.
